name: Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
  # pull_request:
  #   branches: [ main ]
  # schedule:
  #   - cron: "00 23 * * 0"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.2.0

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3.7.1
  
    - name: Login to DockerHub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    #- name: Build and push
    #  uses: docker/build-push-action@v6.10.0
    #  with:
    #    platforms: linux/arm/v7
    #    push: true
    #    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scripted-aws-cli:armv7

    - name: Build and push
      uses: docker/build-push-action@v6.10.0
      with:
        platforms: linux/arm64/v8
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/scripted-aws-cli:armv8